options:
  cache-config: true
  formatter: stylish
  merge-default-rules: false

files:
  include: 'css/**/*.scss'

rules:
  extends-before-declarations: 1
  extends-before-mixins: 1
  force-pseudo-nesting: 1
  no-css-comments: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-transition-all: 1
